/**
 * Schema Updater Engine - Phase 4
 * SchemaUpdateAction Interface
 * 
 * This defines the structure for schema update actions generated by the SchemaUpdaterEngine.
 */

import type { SchemaMappingResult } from '../schema-mapper/SchemaMappingResult';
import type { ReportTypeDefinition } from '../registry/ReportTypeDefinition';

/**
 * Types of schema update actions
 */
export type SchemaUpdateActionType = 
  | 'addField'
  | 'addSection'
  | 'updateSection'
  | 'addTerminology'
  | 'addComplianceRule'
  | 'updateTemplate'
  | 'updateAIGuidance'
  | 'updateReportTypeDefinition'
  | 'addMissingSection'
  | 'addUnknownTerminology'
  | 'fixSchemaGap';

/**
 * Base interface for all schema update actions
 */
export interface SchemaUpdateAction {
  // Core identification
  id: string;
  type: SchemaUpdateActionType;
  target: string; // Target entity (e.g., report type ID, section ID, field ID)
  
  // Action payload
  payload: any; // Type-specific payload data
  
  // Context and reasoning
  reason: string;
  source: 'schema_gap' | 'unmapped_section' | 'missing_section' | 'extra_section' | 'unknown_terminology' | 'manual';
  sourceData?: any; // Original data that triggered this action
  
  // Confidence and validation
  confidence: number; // 0-1 confidence score
  validationStatus: 'pending' | 'validated' | 'rejected' | 'applied';
  validationNotes?: string;
  
  // Timestamps
  createdAt: Date;
  updatedAt: Date;
  appliedAt?: Date;
  
  // Metadata
  priority: 'critical' | 'high' | 'medium' | 'low';
  estimatedImpact: 'major' | 'moderate' | 'minor';
  requiresApproval: boolean;
}

/**
 * Add Field action payload
 */
export interface AddFieldActionPayload {
  fieldId: string;
  fieldName: string;
  fieldType: 'text' | 'number' | 'date' | 'boolean' | 'array' | 'object' | 'section' | 'compliance' | 'terminology';
  parentSectionId: string;
  defaultValue?: any;
  validationRules?: Array<{
    rule: 'required' | 'minLength' | 'maxLength' | 'pattern' | 'custom';
    value?: any;
    message: string;
  }>;
  description?: string;
  aiGuidance?: string;
}

/**
 * Add Section action payload
 */
export interface AddSectionActionPayload {
  sectionId: string;
  sectionName: string;
  description: string;
  required: boolean;
  conditionalLogic?: {
    dependsOn: string;
    condition: 'present' | 'absent' | 'value' | 'contains';
    value?: any;
  };
  template?: string;
  aiGuidance?: string;
  validationRules?: Array<{
    rule: 'required' | 'minLength' | 'maxLength' | 'pattern' | 'custom';
    value?: any;
    message: string;
  }>;
  position?: 'before' | 'after' | 'append';
  relativeToSectionId?: string;
}

/**
 * Update Section action payload
 */
export interface UpdateSectionActionPayload {
  sectionId: string;
  updates: {
    name?: string;
    description?: string;
    required?: boolean;
    conditionalLogic?: {
      dependsOn: string;
      condition: 'present' | 'absent' | 'value' | 'contains';
      value?: any;
    };
    template?: string;
    aiGuidance?: string;
    validationRules?: Array<{
      rule: 'required' | 'minLength' | 'maxLength' | 'pattern' | 'custom';
      value?: any;
      message: string;
    }>;
  };
}

/**
 * Add Terminology action payload
 */
export interface AddTerminologyActionPayload {
  term: string;
  definition: string;
  category: 'technical' | 'legal' | 'compliance' | 'species' | 'measurement' | 'general' | 'unknown';
  synonyms?: string[];
  examples?: string[];
  relatedTerms?: string[];
  source?: string;
}

/**
 * Add Compliance Rule action payload
 */
export interface AddComplianceRuleActionPayload {
  ruleId: string;
  name: string;
  description: string;
  standard: string;
  rule: string;
  validationLogic?: string;
  severity: 'critical' | 'warning' | 'recommendation';
  appliesToSections?: string[];
  appliesToReportTypes?: string[];
}

/**
 * Update Template action payload
 */
export interface UpdateTemplateActionPayload {
  templateId: string;
  templateContent: string;
  templateType: 'section' | 'full' | 'partial';
  appliesToSections?: string[];
  appliesToReportTypes?: string[];
  versionNotes?: string;
}

/**
 * Update AI Guidance action payload
 */
export interface UpdateAIGuidanceActionPayload {
  guidanceId: string;
  purpose: 'generation' | 'validation' | 'enhancement' | 'compliance';
  guidance: string;
  examples?: string[];
  constraints?: string[];
  appliesToSections?: string[];
  appliesToReportTypes?: string[];
}

/**
 * Update Report Type Definition action payload
 */
export interface UpdateReportTypeDefinitionActionPayload {
  reportTypeId: string;
  updates: Partial<ReportTypeDefinition>;
  versionIncrement: 'major' | 'minor' | 'patch';
  updateNotes?: string;
}

/**
 * Add Missing Section action payload
 */
export interface AddMissingSectionActionPayload {
  sectionId: string;
  sectionName: string;
  description: string;
  required: boolean;
  reason: 'not_present' | 'empty' | 'invalid_format' | 'conditional_not_met';
  suggestedContent?: string;
  aiGuidance?: string;
}

/**
 * Add Unknown Terminology action payload
 */
export interface AddUnknownTerminologyActionPayload {
  term: string;
  context: string;
  frequency: number;
  category: 'technical' | 'legal' | 'compliance' | 'species' | 'measurement' | 'general' | 'unknown';
  suggestedDefinition?: string;
  suggestedCategory?: string;
}

/**
 * Fix Schema Gap action payload
 */
export interface FixSchemaGapActionPayload {
  gapId: string;
  type: 'missing_field' | 'missing_section' | 'unknown_section' | 'unknown_terminology' | 'unsupported_structure' | 'mismatched_schema';
  description: string;
  severity: 'critical' | 'warning' | 'info';
  fix: string;
  affectedSectionId?: string;
  affectedFieldId?: string;
  data: any;
}

/**
 * Helper function to create a new SchemaUpdateAction
 */
export function createSchemaUpdateAction(
  type: SchemaUpdateActionType,
  target: string,
  payload: any,
  reason: string,
  source: SchemaUpdateAction['source'],
  confidence: number = 0.8,
  priority: SchemaUpdateAction['priority'] = 'medium'
): Omit<SchemaUpdateAction, 'id' | 'createdAt' | 'updatedAt'> {
  const now = new Date();
  
  return {
    type,
    target,
    payload,
    reason,
    source,
    confidence,
    validationStatus: 'pending',
    priority,
    estimatedImpact: 'moderate',
    requiresApproval: confidence < 0.7,
    sourceData: undefined
  };
}

/**
 * Generate a unique ID for a schema update action
 */
export function generateSchemaUpdateActionId(): string {
  return `update_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`;
}

/**
 * Calculate action priority based on severity and confidence
 */
export function calculateActionPriority(
  severity: 'critical' | 'warning' | 'info',
  confidence: number
): SchemaUpdateAction['priority'] {
  if (severity === 'critical' && confidence > 0.7) return 'critical';
  if (severity === 'critical' && confidence <= 0.7) return 'high';
  if (severity === 'warning' && confidence > 0.7) return 'high';
  if (severity === 'warning' && confidence <= 0.7) return 'medium';
  return 'low';
}

/**
 * Validate a schema update action
 */
export function validateSchemaUpdateAction(action: SchemaUpdateAction): {
  isValid: boolean;
  errors: string[];
  warnings: string[];
} {
  const errors: string[] = [];
  const warnings: string[] = [];
  
  // Basic validation
  if (!action.id) errors.push('Action ID is required');
  if (!action.type) errors.push('Action type is required');
  if (!action.target) errors.push('Target is required');
  if (!action.payload) errors.push('Payload is required');
  if (!action.reason) errors.push('Reason is required');
  
  // Confidence validation
  if (action.confidence < 0 || action.confidence > 1) {
    errors.push('Confidence must be between 0 and 1');
  }
  
  // Type-specific validation
  switch (action.type) {
    case 'addField':
      if (!action.payload.fieldId) errors.push('Field ID is required for addField action');
      if (!action.payload.fieldName) errors.push('Field name is required for addField action');
      break;
    case 'addSection':
      if (!action.payload.sectionId) errors.push('Section ID is required for addSection action');
      if (!action.payload.sectionName) errors.push('Section name is required for addSection action');
      break;
    case 'updateSection':
      if (!action.payload.sectionId) errors.push('Section ID is required for updateSection action');
      if (!action.payload.updates) errors.push('Updates are required for updateSection action');
      break;
  }
  
  // Warning for low confidence
  if (action.confidence < 0.5) {
    warnings.push('Low confidence action - consider manual review');
  }
  
  // Warning for high impact with low confidence
  if (action.estimatedImpact === 'major' && action.confidence < 0.7) {
    warnings.push('Major impact action with low confidence - requires approval');
  }
  
  return {
    isValid: errors.length === 0,
    errors,
    warnings
  };
}