// Supabase Edge Function: export-document
// Generates PDF or Word documents from structured data
// Uses WASM libraries for document generation

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.39.0'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS'
}

// Document types
type DocumentType = 'pdf' | 'docx' | 'html' | 'markdown'

// Export request interface
interface ExportRequest {
  documentType: DocumentType
  content: {
    title: string
    author?: string
    date?: string
    sections: Array<{
      title: string
      content: string
      level: number
    }>
    metadata?: Record<string, any>
    style?: {
      fontFamily?: string
      fontSize?: number
      lineHeight?: number
      margins?: {
        top: number
        right: number
        bottom: number
        left: number
      }
    }
  }
  fileName?: string
  includeHeader?: boolean
  includeFooter?: boolean
}

// Export response interface
interface ExportResponse {
  success: boolean
  documentUrl?: string
  documentData?: string // Base64 encoded for binary formats
  fileName?: string
  error?: string
  fileSize?: number
}

// Generate PDF document (simplified - in production use a proper PDF library)
async function generatePdf(content: ExportRequest['content']): Promise<Uint8Array> {
  // For now, generate a simple HTML that could be converted to PDF
  // In production, use a library like pdf-lib or a WASM PDF generator
  
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>${content.title}</title>
      <style>
        body {
          font-family: ${content.style?.fontFamily || 'Arial, sans-serif'};
          font-size: ${content.style?.fontSize || 12}pt;
          line-height: ${content.style?.lineHeight || 1.5};
          margin: ${content.style?.margins?.top || 20}mm ${content.style?.margins?.right || 20}mm ${content.style?.margins?.bottom || 20}mm ${content.style?.margins?.left || 20}mm;
        }
        h1 { font-size: 24pt; margin-top: 30pt; }
        h2 { font-size: 18pt; margin-top: 20pt; }
        h3 { font-size: 14pt; margin-top: 15pt; }
        .header { text-align: center; border-bottom: 1px solid #ccc; padding-bottom: 10pt; margin-bottom: 20pt; }
        .footer { text-align: center; border-top: 1px solid #ccc; padding-top: 10pt; margin-top: 20pt; font-size: 10pt; color: #666; }
        .section { margin-bottom: 15pt; }
        .metadata { font-size: 10pt; color: #666; margin-bottom: 20pt; }
      </style>
    </head>
    <body>
      ${content.author || content.date ? `
        <div class="header">
          <h1>${content.title}</h1>
          ${content.author ? `<div>Author: ${content.author}</div>` : ''}
          ${content.date ? `<div>Date: ${content.date}</div>` : ''}
        </div>
      ` : `<h1>${content.title}</h1>`}
      
      ${content.metadata && Object.keys(content.metadata).length > 0 ? `
        <div class="metadata">
          ${Object.entries(content.metadata).map(([key, value]) => 
            `<div><strong>${key}:</strong> ${value}</div>`
          ).join('')}
        </div>
      ` : ''}
      
      ${content.sections.map(section => `
        <div class="section">
          <h${section.level + 1}>${section.title}</h${section.level + 1}>
          <div>${section.content}</div>
        </div>
      `).join('')}
      
      <div class="footer">
        Generated by Oscar AI • ${new Date().toLocaleDateString()}
      </div>
    </body>
    </html>
  `
  
  // Convert HTML to Uint8Array (in production, this would generate actual PDF bytes)
  return new TextEncoder().encode(html)
}

// Generate Word document (simplified)
async function generateDocx(content: ExportRequest['content']): Promise<Uint8Array> {
  // For now, generate simple XML structure
  // In production, use a library like docx or mammoth
  
  const xml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <?mso-application progid="Word.Document"?>
    <w:wordDocument xmlns:w="http://schemas.microsoft.com/office/word/2003/wordml">
      <w:body>
        <w:p>
          <w:r>
            <w:t>${content.title}</w:t>
          </w:r>
        </w:p>
        ${content.sections.map(section => `
          <w:p>
            <w:r>
              <w:t>${section.title}</w:t>
            </w:r>
          </w:p>
          <w:p>
            <w:r>
              <w:t>${section.content}</w:t>
            </w:r>
          </w:p>
        `).join('')}
      </w:body>
    </w:wordDocument>
  `
  
  return new TextEncoder().encode(xml)
}

// Generate HTML document
async function generateHtml(content: ExportRequest['content']): Promise<Uint8Array> {
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>${content.title}</title>
      <style>
        body { font-family: ${content.style?.fontFamily || 'Arial, sans-serif'}; max-width: 800px; margin: 0 auto; padding: 20px; }
        h1 { color: #333; border-bottom: 2px solid #eee; padding-bottom: 10px; }
        .section { margin: 20px 0; }
        .metadata { background: #f5f5f5; padding: 10px; border-radius: 5px; margin: 20px 0; }
      </style>
    </head>
    <body>
      <h1>${content.title}</h1>
      
      ${content.author || content.date ? `
        <div>
          ${content.author ? `<div><strong>Author:</strong> ${content.author}</div>` : ''}
          ${content.date ? `<div><strong>Date:</strong> ${content.date}</div>` : ''}
        </div>
      ` : ''}
      
      ${content.metadata && Object.keys(content.metadata).length > 0 ? `
        <div class="metadata">
          ${Object.entries(content.metadata).map(([key, value]) => 
            `<div><strong>${key}:</strong> ${value}</div>`
          ).join('')}
        </div>
      ` : ''}
      
      ${content.sections.map(section => `
        <div class="section">
          <h${section.level + 1}>${section.title}</h${section.level + 1}>
          <div>${section.content}</div>
        </div>
      `).join('')}
      
      <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #666; font-size: 0.9em;">
        Generated by Oscar AI • ${new Date().toLocaleDateString()}
      </footer>
    </body>
    </html>
  `
  
  return new TextEncoder().encode(html)
}

// Generate Markdown document
async function generateMarkdown(content: ExportRequest['content']): Promise<Uint8Array> {
  const markdown = `
# ${content.title}

${content.author ? `**Author:** ${content.author}\n` : ''}
${content.date ? `**Date:** ${content.date}\n` : ''}

${content.metadata && Object.keys(content.metadata).length > 0 ? 
  Object.entries(content.metadata).map(([key, value]) => `**${key}:** ${value}\n`).join('') + '\n' : ''}

${content.sections.map(section => 
  `${'#'.repeat(section.level + 1)} ${section.title}\n\n${section.content}\n\n`
).join('')}

---
*Generated by Oscar AI • ${new Date().toLocaleDateString()}*
  `.trim()
  
  return new TextEncoder().encode(markdown)
}

// Handle OPTIONS request (CORS preflight)
function handleOptions(): Response {
  return new Response(null, {
    headers: corsHeaders,
    status: 204
  })
}

// Handle POST request
async function handlePost(request: Request): Promise<Response> {
  try {
    // Get user ID from JWT
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      throw new Error('Missing authorization header')
    }
    
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )
    
    // Verify JWT and get user
    const jwt = authHeader.replace('Bearer ', '')
    const { data: { user }, error } = await supabaseClient.auth.getUser(jwt)
    
    if (error || !user) {
      throw new Error('Invalid authentication')
    }
    
    // Parse request body
    const body: ExportRequest = await request.json()
    
    // Validate request
    if (!body.documentType || !body.content || !body.content.title || !body.content.sections) {
      throw new Error('Missing required fields: documentType, content.title, content.sections')
    }
    
    // Generate document based on type
    let documentData: Uint8Array
    let mimeType: string
    let fileExtension: string
    
    switch (body.documentType) {
      case 'pdf':
        documentData = await generatePdf(body.content)
        mimeType = 'application/pdf'
        fileExtension = 'pdf'
        break
      case 'docx':
        documentData = await generateDocx(body.content)
        mimeType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
        fileExtension = 'docx'
        break
      case 'html':
        documentData = await generateHtml(body.content)
        mimeType = 'text/html'
        fileExtension = 'html'
        break
      case 'markdown':
        documentData = await generateMarkdown(body.content)
        mimeType = 'text/markdown'
        fileExtension = 'md'
        break
      default:
        throw new Error(`Unsupported document type: ${body.documentType}`)
    }
    
    // Generate file name
    const fileName = body.fileName || 
      `${body.content.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${Date.now()}.${fileExtension}`
    
    // Convert to base64 for response
    const base64Data = btoa(String.fromCharCode(...documentData))
    
    // Store in Supabase Storage if needed (optional)
    let documentUrl: string | undefined
    
    if (body.documentType === 'pdf' || body.documentType === 'docx') {
      try {
        // Upload to Supabase Storage
        const filePath = `exports/${user.id}/${fileName}`
        const { error: uploadError } = await supabaseClient.storage
          .from('documents')
          .upload(filePath, documentData, {
            contentType: mimeType,
            upsert: true
          })
        
        if (!uploadError) {
          // Get public URL
          const { data: urlData } = supabaseClient.storage
            .from('documents')
            .getPublicUrl(filePath)
          
          documentUrl = urlData.publicUrl
        }
      } catch (storageError) {
        console.warn('Failed to store document in storage:', storageError)
        // Continue without storage
      }
    }
    
    // Prepare response
    const response: ExportResponse = {
      success: true,
      documentUrl,
      documentData: base64Data,
      fileName,
      fileSize: documentData.length
    }
    
    // Return as JSON with base64 data, or as binary if requested
    const acceptHeader = request.headers.get('Accept')
    const returnBinary = acceptHeader?.includes(mimeType)
    
    if (returnBinary) {
      // Return binary file
      return new Response(documentData, {
        headers: {
          ...corsHeaders,
          'Content-Type': mimeType,
          'Content-Disposition': `attachment; filename="${fileName}"`,
          'Content-Length': documentData.length.toString()
        }
      })
    } else {
      // Return JSON with base64 data
      return new Response(JSON.stringify(response), {
        headers: {
          ...corsHeaders,
          'Content-Type': 'application/json'
        }
      })
    }
    
  } catch (error: any) {
    console.error('Export error:', error)
    
    const errorResponse: ExportResponse = {
      success: false,
      error: error.message || 'Internal server error'
    }
    
    return new Response(JSON.stringify(errorResponse), {
      headers: {
        ...corsHeaders,
        'Content-Type': 'application/json'
      },
      status: 500
    })
  }
}

// Main handler
serve(async (req: Request) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return handleOptions()
  }
  
  // Only allow POST requests
  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 405
    })
  }
  
  // Handle POST request
  return handlePost(req)
})