/**
 * Clarifying Question – a question generated by the AI Reasoning Engine
 * to resolve ambiguities, missing information, or contradictions.
 */

export type ExpectedAnswerType =
	| 'text'
	| 'number'
	| 'date'
	| 'boolean'
	| 'choice'
	| 'list'
	| 'section'
	| 'field'
	| 'methodology'
	| 'complianceReference';

export interface ClarifyingQuestion {
	/** Unique identifier for this question */
	id: string;
	/** The question text */
	question: string;
	/** Reason why this question is being asked */
	reason: string;
	/** Target of the question (e.g., section name, field name, paragraph index) */
	target: string;
	/** Expected type of answer */
	expectedAnswerType: ExpectedAnswerType;
	/** Optional choices for 'choice' answer type */
	choices?: string[];
	/** Timestamps */
	timestamps: {
		created: Date;
		answered?: Date;
	};
	/** Optional answer provided by the user */
	answer?: string;
	/** Optional confidence that this question is needed (0‑1) */
	confidence?: number;
	/** Optional references to source data that triggered the question */
	sourceReferences?: string[];
}

/**
 * Create a new ClarifyingQuestion with default timestamps.
 */
export function createClarifyingQuestion(
	question: string,
	reason: string,
	target: string,
	expectedAnswerType: ExpectedAnswerType = 'text',
	choices?: string[],
	confidence?: number,
	sourceReferences?: string[]
): ClarifyingQuestion {
	const now = new Date();
	return {
		id: `question_${now.getTime()}_${Math.random().toString(36).substring(2, 9)}`,
		question,
		reason,
		target,
		expectedAnswerType,
		choices,
		timestamps: { created: now },
		confidence,
		sourceReferences,
	};
}

/**
 * Validate that a ClarifyingQuestion has all required fields.
 */
export function validateClarifyingQuestion(question: any): question is ClarifyingQuestion {
	if (!question.id || typeof question.id !== 'string') return false;
	if (!question.question || typeof question.question !== 'string') return false;
	if (!question.reason || typeof question.reason !== 'string') return false;
	if (!question.target || typeof question.target !== 'string') return false;
	if (!question.expectedAnswerType || !['text', 'number', 'date', 'boolean', 'choice', 'list', 'section', 'field', 'methodology', 'complianceReference'].includes(question.expectedAnswerType)) return false;
	if (!question.timestamps || !question.timestamps.created || !(question.timestamps.created instanceof Date)) return false;
	return true;
}

/**
 * Mark a question as answered.
 */
export function answerClarifyingQuestion(question: ClarifyingQuestion, answer: string): ClarifyingQuestion {
	return {
		...question,
		answer,
		timestamps: {
			...question.timestamps,
			answered: new Date(),
		},
	};
}