/**
 * Reasoning Insight – a single insight generated by the AI Reasoning Engine.
 * 
 * Insights represent detected issues, suggestions, warnings, or improvements
 * about a report's structure, content, style, compliance, terminology, metadata,
 * or methodology.
 */

export type InsightType =
	| 'missingInfo'
	| 'contradiction'
	| 'ambiguity'
	| 'suggestion'
	| 'warning'
	| 'improvement'
	| 'complianceIssue'
	| 'styleIssue';

export type InsightSeverity = 'low' | 'medium' | 'high' | 'critical';

export interface ReasoningInsight {
	/** Unique identifier for this insight */
	id: string;
	/** Type of insight */
	type: InsightType;
	/** Human‑readable message describing the insight */
	message: string;
	/** Target of the insight (e.g., section name, field name, paragraph index) */
	target: string;
	/** Recommended actions to address the insight */
	recommendedActions: string[];
	/** Severity level */
	severity: InsightSeverity;
	/** Timestamps */
	timestamps: {
		created: Date;
		updated?: Date;
	};
	/** Optional confidence score (0‑1) */
	confidence?: number;
	/** Optional references to source data (e.g., decompiled report section ID) */
	sourceReferences?: string[];
}

/**
 * Create a new ReasoningInsight with default timestamps.
 */
export function createReasoningInsight(
	type: InsightType,
	message: string,
	target: string,
	recommendedActions: string[] = [],
	severity: InsightSeverity = 'medium',
	confidence?: number,
	sourceReferences?: string[]
): ReasoningInsight {
	const now = new Date();
	return {
		id: `insight_${now.getTime()}_${Math.random().toString(36).substring(2, 9)}`,
		type,
		message,
		target,
		recommendedActions,
		severity,
		timestamps: { created: now },
		confidence,
		sourceReferences,
	};
}

/**
 * Validate that a ReasoningInsight has all required fields.
 */
export function validateReasoningInsight(insight: any): insight is ReasoningInsight {
	if (!insight.id || typeof insight.id !== 'string') return false;
	if (!insight.type || !['missingInfo', 'contradiction', 'ambiguity', 'suggestion', 'warning', 'improvement', 'complianceIssue', 'styleIssue'].includes(insight.type)) return false;
	if (!insight.message || typeof insight.message !== 'string') return false;
	if (!insight.target || typeof insight.target !== 'string') return false;
	if (!Array.isArray(insight.recommendedActions)) return false;
	if (!insight.severity || !['low', 'medium', 'high', 'critical'].includes(insight.severity)) return false;
	if (!insight.timestamps || !insight.timestamps.created || !(insight.timestamps.created instanceof Date)) return false;
	return true;
}