// HTML Snapshot Export Utility
// Captures DOM elements as standalone HTML files with styles

import type { ExportContent } from './types'

/**
 * Options for HTML snapshot generation
 */
export interface HtmlSnapshotOptions {
  includeStyles?: boolean
  includeMeta?: boolean
  title?: string
  filename?: string
  captureFullPage?: boolean
  preserveIds?: boolean
  inlineStyles?: boolean
}

/**
 * Default options
 */
const DEFAULT_OPTIONS: HtmlSnapshotOptions = {
  includeStyles: true,
  includeMeta: true,
  title: 'Snapshot',
  filename: `snapshot_${Date.now()}.html`,
  captureFullPage: false,
  preserveIds: true,
  inlineStyles: false
}

/**
 * Extract CSS styles from document
 */
function extractStyles(): string {
  const styles: string[] = []
  
  // Get all style sheets
  for (const sheet of document.styleSheets) {
    try {
      // Skip cross-origin stylesheets that throw security errors
      const rules = sheet.cssRules || sheet.rules
      if (rules) {
        for (const rule of rules) {
          styles.push(rule.cssText)
        }
      }
    } catch (error) {
      // Silently skip stylesheets that can't be accessed
      console.warn('Could not access stylesheet:', sheet.href)
    }
  }
  
  return styles.join('\n')
}

/**
 * Get computed styles for an element as inline style attribute
 */
function getInlineStyles(element: HTMLElement): string {
  const computed = window.getComputedStyle(element)
  const styles: string[] = []
  
  // Copy relevant styles (simplified)
  const styleProps = [
    'color', 'backgroundColor', 'fontFamily', 'fontSize', 'fontWeight',
    'margin', 'padding', 'border', 'display', 'position', 'width', 'height',
    'flexDirection', 'justifyContent', 'alignItems', 'gap'
  ]
  
  for (const prop of styleProps) {
    const value = computed.getPropertyValue(prop)
    if (value && value !== 'none' && value !== 'auto') {
      styles.push(`${prop}: ${value}`)
    }
  }
  
  return styles.join('; ')
}

/**
 * Clone element and its children, optionally preserving IDs and styles
 */
function cloneElementWithStyles(
  element: HTMLElement,
  options: HtmlSnapshotOptions
): HTMLElement {
  const clone = element.cloneNode(true) as HTMLElement
  
  if (options.inlineStyles) {
    const inlineStyle = getInlineStyles(element)
    if (inlineStyle) {
      clone.setAttribute('style', inlineStyle)
    }
  }
  
  if (!options.preserveIds) {
    clone.removeAttribute('id')
  }
  
  // Recursively process children
  const children = clone.querySelectorAll('*')
  children.forEach(child => {
    if (!options.preserveIds) {
      child.removeAttribute('id')
    }
    if (options.inlineStyles) {
      const childInlineStyle = getInlineStyles(child as HTMLElement)
      if (childInlineStyle) {
        child.setAttribute('style', childInlineStyle)
      }
    }
  })
  
  return clone
}

/**
 * Generate HTML snapshot from an element or selector
 */
export function generateHtmlSnapshot(
  elementOrSelector: HTMLElement | string,
  options: Partial<HtmlSnapshotOptions> = {}
): string {
  const opts = { ...DEFAULT_OPTIONS, ...options }
  
  let element: HTMLElement
  if (typeof elementOrSelector === 'string') {
    const found = document.querySelector(elementOrSelector) as HTMLElement
    if (!found) {
      throw new Error(`Element not found: ${elementOrSelector}`)
    }
    element = found
  } else {
    element = elementOrSelector
  }
  
  // Clone the element
  const clonedElement = opts.captureFullPage 
    ? document.documentElement.cloneNode(true) as HTMLElement
    : cloneElementWithStyles(element, opts)
  
  // Extract styles
  let styles = ''
  if (opts.includeStyles) {
    styles = opts.inlineStyles ? '' : `<style>\n${extractStyles()}\n</style>`
  }
  
  // Build HTML
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  ${opts.includeMeta ? '<meta name="generator" content="Oscar AI HTML Snapshot">' : ''}
  <title>${opts.title}</title>
  ${styles}
</head>
<body>
  ${opts.captureFullPage ? clonedElement.outerHTML : clonedElement.outerHTML}
  <footer style="margin-top: 2rem; padding: 1rem; text-align: center; color: #666; font-size: 0.875rem; border-top: 1px solid #eee;">
    Generated by Oscar AI • ${new Date().toLocaleDateString()}
  </footer>
</body>
</html>
  `.trim()
  
  return html
}

/**
 * Download HTML snapshot as a file
 */
export function downloadHtmlSnapshot(
  elementOrSelector: HTMLElement | string,
  options: Partial<HtmlSnapshotOptions> = {}
): void {
  try {
    const html = generateHtmlSnapshot(elementOrSelector, options)
    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = options.filename || DEFAULT_OPTIONS.filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  } catch (error) {
    console.error('Failed to generate HTML snapshot:', error)
    throw error
  }
}

/**
 * Create a snapshot of the current page (full page)
 */
export function snapshotCurrentPage(options: Partial<HtmlSnapshotOptions> = {}): string {
  return generateHtmlSnapshot(document.documentElement, {
    captureFullPage: true,
    title: document.title || 'Page Snapshot',
    filename: `page_snapshot_${Date.now()}.html`,
    ...options
  })
}

/**
 * Convert ExportContent to HTML string
 */
export function exportContentToHtml(content: ExportContent): string {
  const sectionsHtml = content.sections
    .map(section => {
      const tag = `h${Math.min(6, section.level + 1)}`
      return `
        <${tag}>${section.title}</${tag}>
        <div>${section.content}</div>
      `
    })
    .join('\n')

  const metadataHtml = content.metadata
    ? Object.entries(content.metadata)
        .map(([key, value]) => `<div><strong>${key}:</strong> ${value}</div>`)
        .join('')
    : ''

  return `
    ${metadataHtml ? `<div class="metadata">${metadataHtml}</div>` : ''}
    <div class="content">
      ${sectionsHtml}
    </div>
  `.trim()
}

/**
 * Create a snapshot of a report/note for export
 */
export function snapshotForExport(
  content: { title: string; html: string; metadata?: Record<string, any> } | ExportContent,
  options: Partial<HtmlSnapshotOptions> = {}
): string {
  let title: string
  let html: string
  let metadata: Record<string, any> | undefined

  if ('sections' in content) {
    // It's ExportContent
    title = content.title
    html = exportContentToHtml(content)
    metadata = content.metadata
  } else {
    // It's the old format
    title = content.title
    html = content.html
    metadata = content.metadata
  }

  const metadataHtml = metadata
    ? Object.entries(metadata)
        .map(([key, value]) => `<div><strong>${key}:</strong> ${value}</div>`)
        .join('')
    : ''
  
  const fullHtml = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; }
    h1 { color: #111827; border-bottom: 2px solid #eee; padding-bottom: 1rem; }
    .metadata { background: #f9fafb; padding: 1rem; border-radius: 8px; margin: 1rem 0; }
    .content { line-height: 1.6; }
    footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #eee; color: #666; font-size: 0.875rem; text-align: center; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  ${metadataHtml ? `<div class="metadata">${metadataHtml}</div>` : ''}
  <div class="content">${html}</div>
  <footer>
    Generated by Oscar AI • ${new Date().toLocaleDateString()}
  </footer>
</body>
</html>
  `
  
  return fullHtml.trim()
}