// Markdown Export Utility
// Converts structured content to Markdown format

import type { ExportContent } from './types'

/**
 * Options for Markdown generation
 */
export interface MarkdownOptions {
  includeMetadata?: boolean
  includeHeader?: boolean
  includeFooter?: boolean
  filename?: string
}

/**
 * Default options
 */
const DEFAULT_OPTIONS: MarkdownOptions = {
  includeMetadata: true,
  includeHeader: true,
  includeFooter: true,
  filename: `export_${Date.now()}.md`
}

/**
 * Convert ExportContent to Markdown string
 */
export function exportContentToMarkdown(content: ExportContent, options: MarkdownOptions = {}): string {
  const opts = { ...DEFAULT_OPTIONS, ...options }
  
  const lines: string[] = []
  
  // Title
  if (opts.includeHeader) {
    lines.push(`# ${content.title}`)
    lines.push('')
  }
  
  // Metadata
  if (opts.includeMetadata && content.metadata) {
    lines.push('## Metadata')
    for (const [key, value] of Object.entries(content.metadata)) {
      lines.push(`- **${key}:** ${value}`)
    }
    lines.push('')
  }
  
  // Author and date
  if (content.author) {
    lines.push(`**Author:** ${content.author}`)
    lines.push('')
  }
  if (content.date) {
    lines.push(`**Date:** ${content.date}`)
    lines.push('')
  }
  
  // Sections
  for (const section of content.sections) {
    const headingLevel = Math.min(6, section.level + 1)
    const headingPrefix = '#'.repeat(headingLevel)
    lines.push(`${headingPrefix} ${section.title}`)
    lines.push('')
    lines.push(section.content)
    lines.push('')
  }
  
  // Footer
  if (opts.includeFooter) {
    lines.push('---')
    lines.push(`*Generated by Oscar AI • ${new Date().toLocaleDateString()}*`)
  }
  
  return lines.join('\n').trim()
}

/**
 * Convert HTML string to Markdown (simplified)
 * This is a basic conversion; for more robust conversion consider using a library
 */
export function htmlToMarkdown(html: string): string {
  // Very basic conversion for demonstration
  let markdown = html
    .replace(/<h1[^>]*>(.*?)<\/h1>/gi, '# $1\n')
    .replace(/<h2[^>]*>(.*?)<\/h2>/gi, '## $1\n')
    .replace(/<h3[^>]*>(.*?)<\/h3>/gi, '### $1\n')
    .replace(/<h4[^>]*>(.*?)<\/h4>/gi, '#### $1\n')
    .replace(/<h5[^>]*>(.*?)<\/h5>/gi, '##### $1\n')
    .replace(/<h6[^>]*>(.*?)<\/h6>/gi, '###### $1\n')
    .replace(/<p[^>]*>(.*?)<\/p>/gi, '$1\n')
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<strong[^>]*>(.*?)<\/strong>/gi, '**$1**')
    .replace(/<b[^>]*>(.*?)<\/b>/gi, '**$1**')
    .replace(/<em[^>]*>(.*?)<\/em>/gi, '*$1*')
    .replace(/<i[^>]*>(.*?)<\/i>/gi, '*$1*')
    .replace(/<code[^>]*>(.*?)<\/code>/gi, '`$1`')
    .replace(/<a[^>]*href="([^"]*)"[^>]*>(.*?)<\/a>/gi, '[$2]($1)')
    .replace(/<ul[^>]*>(.*?)<\/ul>/gis, (match, content) => {
      return content.replace(/<li[^>]*>(.*?)<\/li>/gi, '- $1\n')
    })
    .replace(/<ol[^>]*>(.*?)<\/ol>/gis, (match, content) => {
      let index = 1
      return content.replace(/<li[^>]*>(.*?)<\/li>/gi, () => `${index++}. $1\n`)
    })
    .replace(/<[^>]+>/g, '') // Remove any remaining tags
    .replace(/&nbsp;/g, ' ')
    .replace(/&/g, '&')
    .replace(/</g, '<')
    .replace(/>/g, '>')
    .replace(/"/g, '"')
    .replace(/'/g, "'")
    .trim()
  
  // Collapse multiple newlines
  markdown = markdown.replace(/\n{3,}/g, '\n\n')
  
  return markdown
}

/**
 * Download Markdown as a file
 */
export function downloadMarkdown(markdown: string, filename: string = DEFAULT_OPTIONS.filename!): void {
  try {
    const blob = new Blob([markdown], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  } catch (error) {
    console.error('Failed to download Markdown:', error)
    throw error
  }
}

/**
 * Export content as Markdown file (convenience function)
 */
export function exportAsMarkdown(content: ExportContent, options: MarkdownOptions = {}): void {
  const markdown = exportContentToMarkdown(content, options)
  downloadMarkdown(markdown, options.filename || DEFAULT_OPTIONS.filename)
}

/**
 * Create a Markdown export from HTML content
 */
export function exportHtmlAsMarkdown(html: string, title: string, options: MarkdownOptions = {}): void {
  const markdown = htmlToMarkdown(html)
  const content: ExportContent = {
    title,
    sections: [
      {
        title: 'Content',
        content: markdown,
        level: 1
      }
    ],
    metadata: {
      source: 'HTML conversion',
      convertedAt: new Date().toISOString()
    }
  }
  exportAsMarkdown(content, options)
}