import type { LayoutBlock } from '../layout/LayoutTypes';
import type { DocumentEvent, DocumentCommand, DocumentTone, DocumentSection, Inconsistency } from './DocumentTypes';
import { DocumentAwareContextMode } from './DocumentAwareContextMode';

type EventListener = (event: DocumentEvent) => void;

/**
 * Document event model – listens for document‑focused events and emits document‑level commands.
 */
export class DocumentEventModel {
  private listeners = new Map<string, EventListener[]>();
  private contextMode: DocumentAwareContextMode;

  constructor() {
    this.contextMode = new DocumentAwareContextMode();
  }

  /**
   * Subscribe to a specific event type.
   */
  on(eventType: DocumentEvent['type'], listener: EventListener): void {
    const list = this.listeners.get(eventType) || [];
    list.push(listener);
    this.listeners.set(eventType, list);
  }

  /**
   * Unsubscribe from an event type.
   */
  off(eventType: DocumentEvent['type'], listener: EventListener): void {
    const list = this.listeners.get(eventType);
    if (!list) return;
    const index = list.indexOf(listener);
    if (index >= 0) list.splice(index, 1);
  }

  /**
   * Emit an event to all subscribers.
   */
  emit(event: DocumentEvent): void {
    const list = this.listeners.get(event.type) || [];
    list.forEach(listener => listener(event));

    // Automatically trigger appropriate commands based on event
    this.autoReact(event);
  }

  /**
   * Automatic reaction to events (e.g., on inconsistency detection → fix).
   */
  private autoReact(event: DocumentEvent): void {
    switch (event.type) {
      case 'inconsistencyDetected':
        // Type guard ensures event is InconsistencyDetectedEvent
        if (event.inconsistencies.length > 0) {
          // In a real implementation, you might ask the user before fixing.
          // For now, we just log.
          console.log(`Detected ${event.inconsistencies.length} inconsistencies.`);
        }
        break;
      case 'toneChange':
        console.log(`Tone changed to ${event.tone}.`);
        break;
      case 'documentChange':
        // Optionally trigger structure analysis
        break;
      case 'sectionChange':
        // Optionally trigger cross‑section consistency check
        break;
      case 'mediaAdded':
        // Optionally trigger layout‑aware media placement
        break;
      case 'layoutChange':
        // Optionally trigger structural optimisation
        break;
      default:
        // No auto‑reaction
        break;
    }
  }

  /**
   * Execute a document command and emit resulting events.
   */
  execute(command: DocumentCommand, currentBlocks: LayoutBlock[]): LayoutBlock[] {
    const result = this.contextMode.execute(command, currentBlocks);
    // Emit the events generated by the execution
    result.events.forEach(event => this.emit(event));
    return result.blocks;
  }

  /**
   * Helper: emit a documentOpen event.
   */
  documentOpen(document: any): void {
    this.emit({ type: 'documentOpen', document });
  }

  /**
   * Helper: emit a documentChange event.
   */
  documentChange(blocks: LayoutBlock[]): void {
    this.emit({ type: 'documentChange', blocks });
  }

  /**
   * Helper: emit a sectionChange event.
   */
  sectionChange(section: DocumentSection): void {
    this.emit({ type: 'sectionChange', section });
  }

  /**
   * Helper: emit a toneChange event.
   */
  toneChange(tone: DocumentTone): void {
    this.emit({ type: 'toneChange', tone });
  }

  /**
   * Helper: emit a mediaAdded event.
   */
  mediaAdded(media: any): void {
    this.emit({ type: 'mediaAdded', media });
  }

  /**
   * Helper: emit a layoutChange event.
   */
  layoutChange(block: LayoutBlock): void {
    this.emit({ type: 'layoutChange', block });
  }

  /**
   * Helper: emit an inconsistencyDetected event.
   */
  inconsistencyDetected(inconsistencies: Inconsistency[]): void {
    this.emit({ type: 'inconsistencyDetected', inconsistencies });
  }

  /**
   * Helper: emit a summaryGenerated event.
   */
  summaryGenerated(summary: string, options: any): void {
    this.emit({ type: 'summaryGenerated', summary, options });
  }

  /**
   * Helper: emit a rewriteApplied event.
   */
  rewriteApplied(originalBlocks: LayoutBlock[], newBlocks: LayoutBlock[], options: any): void {
    this.emit({ type: 'rewriteApplied', originalBlocks, newBlocks, options });
  }

  /**
   * Helper: emit a structureOptimised event.
   */
  structureOptimised(suggestions: any[], applied: boolean): void {
    this.emit({ type: 'structureOptimised', suggestions, applied });
  }

  /**
   * Get the current listener count for a given event type.
   */
  listenerCount(eventType: DocumentEvent['type']): number {
    return this.listeners.get(eventType)?.length || 0;
  }

  /**
   * Remove all listeners.
   */
  clearListeners(): void {
    this.listeners.clear();
  }
}