/**
 * Cover page template definition.
 */
export interface CoverPageTemplate {
	id: string;
	name: string;
	description: string;
	html: string;
	css: string;
	variables: string[]; // e.g., ['title', 'subtitle', 'author', 'date', 'client', 'logo']
}

/**
 * Default cover page templates.
 */
export const defaultTemplates: CoverPageTemplate[] = [
	{
		id: 'professional',
		name: 'Professional',
		description: 'Clean, professional cover page with logo and metadata',
		html: `
<div class="cover-page professional">
  <div class="cover-header">
    {{#logo}}<img src="{{logo}}" alt="Logo" class="cover-logo">{{/logo}}
    <h1 class="cover-title">{{title}}</h1>
    {{#subtitle}}<h2 class="cover-subtitle">{{subtitle}}</h2>{{/subtitle}}
  </div>
  <div class="cover-body">
    <div class="cover-metadata">
      {{#author}}<div class="metadata-row"><strong>Author:</strong> {{author}}</div>{{/author}}
      {{#date}}<div class="metadata-row"><strong>Date:</strong> {{date}}</div>{{/date}}
      {{#client}}<div class="metadata-row"><strong>Client:</strong> {{client}}</div>{{/client}}
      {{#project}}<div class="metadata-row"><strong>Project:</strong> {{project}}</div>{{/project}}
      {{#version}}<div class="metadata-row"><strong>Version:</strong> {{version}}</div>{{/version}}
    </div>
  </div>
  <div class="cover-footer">
    <p class="footer-note">Generated by Oscar AI</p>
  </div>
</div>`,
		css: `
.cover-page.professional {
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  align-items: center;
  text-align: center;
  padding: 40mm 20mm;
  box-sizing: border-box;
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}
.cover-header {
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}
.cover-logo {
  max-width: 80mm;
  max-height: 40mm;
  margin-bottom: 20mm;
}
.cover-title {
  font-size: 36pt;
  font-weight: 700;
  margin: 0 0 10mm 0;
  color: #1a1a1a;
}
.cover-subtitle {
  font-size: 20pt;
  font-weight: 400;
  margin: 0;
  color: #666;
}
.cover-body {
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}
.cover-metadata {
  text-align: left;
  font-size: 14pt;
  line-height: 1.8;
  color: #333;
}
.metadata-row {
  margin-bottom: 5mm;
}
.metadata-row strong {
  display: inline-block;
  width: 80mm;
  color: #555;
}
.cover-footer {
  flex: 0;
  font-size: 11pt;
  color: #999;
  margin-top: 20mm;
}`,
		variables: ['title', 'subtitle', 'author', 'date', 'client', 'project', 'version', 'logo']
	},
	{
		id: 'minimal',
		name: 'Minimal',
		description: 'Minimal cover page with title only',
		html: `
<div class="cover-page minimal">
  <div class="cover-content">
    <h1>{{title}}</h1>
    {{#subtitle}}<h2>{{subtitle}}</h2>{{/subtitle}}
    {{#author}}<p class="author">{{author}}</p>{{/author}}
    {{#date}}<p class="date">{{date}}</p>{{/date}}
  </div>
</div>`,
		css: `
.cover-page.minimal {
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  text-align: center;
  font-family: 'Georgia', serif;
}
.cover-content h1 {
  font-size: 48pt;
  font-weight: 300;
  margin: 0 0 10mm 0;
  color: #222;
}
.cover-content h2 {
  font-size: 24pt;
  font-weight: 300;
  margin: 0 0 20mm 0;
  color: #666;
}
.cover-content .author,
.cover-content .date {
  font-size: 14pt;
  color: #888;
  margin: 2mm 0;
}`,
		variables: ['title', 'subtitle', 'author', 'date']
	},
	{
		id: 'corporate',
		name: 'Corporate',
		description: 'Corporate‑style cover page with header and footer',
		html: `
<div class="cover-page corporate">
  <div class="corporate-header">
    <div class="header-left">{{companyName}}</div>
    <div class="header-right">{{documentType}}</div>
  </div>
  <div class="corporate-main">
    <h1>{{title}}</h1>
    <div class="divider"></div>
    <h2>{{subtitle}}</h2>
    <div class="metadata">
      <div><strong>Prepared for:</strong> {{client}}</div>
      <div><strong>Prepared by:</strong> {{author}}</div>
      <div><strong>Date:</strong> {{date}}</div>
      <div><strong>Reference:</strong> {{reference}}</div>
    </div>
  </div>
  <div class="corporate-footer">
    <div class="footer-left">{{confidentiality}}</div>
    <div class="footer-right">{{pageNumber}}</div>
  </div>
</div>`,
		css: `
.cover-page.corporate {
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  font-family: 'Arial', sans-serif;
  background: #f9f9f9;
}
.corporate-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 10mm 20mm;
  border-bottom: 2px solid #ccc;
  font-size: 12pt;
  color: #555;
}
.corporate-main {
  flex: 1;
  padding: 40mm 20mm;
  text-align: center;
}
.corporate-main h1 {
  font-size: 32pt;
  font-weight: 700;
  margin: 0 0 10mm 0;
  color: #1a3d6d;
}
.corporate-main .divider {
  width: 80mm;
  height: 2px;
  background: #1a3d6d;
  margin: 10mm auto;
}
.corporate-main h2 {
  font-size: 18pt;
  font-weight: 400;
  margin: 0 0 20mm 0;
  color: #333;
}
.corporate-main .metadata {
  text-align: left;
  max-width: 120mm;
  margin: 0 auto;
  font-size: 12pt;
  line-height: 2;
}
.corporate-main .metadata div strong {
  display: inline-block;
  width: 40mm;
  color: #666;
}
.corporate-footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 5mm 20mm;
  border-top: 1px solid #ccc;
  font-size: 10pt;
  color: #777;
}`,
		variables: [
			'companyName',
			'documentType',
			'title',
			'subtitle',
			'client',
			'author',
			'date',
			'reference',
			'confidentiality',
			'pageNumber'
		]
	}
];