import { execSync } from 'child_process';
import { writeFileSync } from 'fs';
import { join } from 'path';

// Get git commit hash
function getGitCommitHash() {
	try {
		return execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
	} catch (error) {
		console.warn('Could not get git commit hash:', error.message);
		return 'unknown';
	}
}

// Get current timestamp
function getCurrentTimestamp() {
	return new Date().toISOString();
}

// Read package.json for version
function getPackageVersion() {
	try {
		const packageJson = JSON.parse(execSync('cat package.json', { encoding: 'utf8' }));
		return packageJson.version || '1.0.0';
	} catch (error) {
		console.warn('Could not read package.json:', error.message);
		return '1.0.0';
	}
}

// Generate version file content
function generateVersionFile() {
	const commitHash = getGitCommitHash();
	const timestamp = getCurrentTimestamp();
	const appVersion = getPackageVersion();
	
	const content = `// Auto-generated version information
// This file is generated at build time by generate-version.js script
// DO NOT EDIT THIS FILE MANUALLY

export const APP_VERSION = '${appVersion}';
export const COMMIT_HASH = '${commitHash}';
export const BUILD_TIMESTAMP = '${timestamp}';
export const BUILD_VERSION = \`v\${APP_VERSION} (\${COMMIT_HASH})\`;

// For display in UI
export function getVersionInfo() {
	return {
		version: APP_VERSION,
		commit: COMMIT_HASH,
		timestamp: BUILD_TIMESTAMP,
		full: BUILD_VERSION
	};
}
`;

	return content;
}

// Write version file
function writeVersionFile() {
	const versionContent = generateVersionFile();
	const versionPath = join(process.cwd(), 'src', 'version.ts');
	
	writeFileSync(versionPath, versionContent, 'utf8');
	console.log(`Version file generated at ${versionPath}`);
	console.log(`Version: v${getPackageVersion()} (${getGitCommitHash()})`);
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
	writeVersionFile();
}

export { writeVersionFile, generateVersionFile };