/**
 * DOCX Export Utility
 * 
 * Creates a simple DOCX file from HTML content.
 * Uses basic DOCX structure (Office Open XML) with minimal styling.
 */

interface ExportOptions {
  fileName?: string
  title?: string
  author?: string
  company?: string
}

/**
 * Convert HTML to plain text (removing HTML tags)
 */
function htmlToPlainText(html: string): string {
  const tempDiv = document.createElement('div')
  tempDiv.innerHTML = html
  return tempDiv.textContent || tempDiv.innerText || ''
}

/**
 * Create a simple DOCX file from HTML content
 * Uses Office Open XML format with minimal styling
 */
export async function exportDocx(html: string, options: ExportOptions = {}): Promise<void> {
  const fileName = options.fileName || `report-${Date.now()}.docx`
  const title = options.title || 'Report'
  const author = options.author || 'Oscar AI'
  const company = options.company || 'Arboricultural Services'
  
  // Convert HTML to plain text for simple DOCX
  const plainText = htmlToPlainText(html)
  
  // Create a simple DOCX structure (Office Open XML)
  // This is a minimal DOCX that will open in Word
  const docxContent = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?mso-application progid="Word.Document"?>
<w:wordDocument 
  xmlns:w="http://schemas.microsoft.com/office/word/2003/wordml"
  xmlns:v="urn:schemas-microsoft-com:vml"
  xmlns:w10="urn:schemas-microsoft-com:office:word"
  xmlns:sl="http://schemas.microsoft.com/schemaLibrary/2003/core"
  xmlns:aml="http://schemas.microsoft.com/aml/2001/core"
  xmlns:wx="http://schemas.microsoft.com/office/word/2003/auxHint"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882">
  
  <o:DocumentProperties>
    <o:Title>${title}</o:Title>
    <o:Author>${author}</o:Author>
    <o:Company>${company}</o:Company>
    <o:Created>${new Date().toISOString()}</o:Created>
  </o:DocumentProperties>
  
  <w:fonts>
    <w:defaultFonts w:ascii="Calibri" w:fareast="Calibri" w:h-ansi="Calibri" w:cs="Calibri"/>
  </w:fonts>
  
  <w:styles>
    <w:style w:type="paragraph" w:default="on" w:styleId="Normal">
      <w:name w:val="Normal"/>
      <w:rPr>
        <w:rFonts w:ascii="Calibri" w:h-ansi="Calibri"/>
        <w:sz w:val="24"/>
        <w:sz-cs w:val="24"/>
      </w:rPr>
    </w:style>
    
    <w:style w:type="paragraph" w:styleId="Heading1">
      <w:name w:val="heading 1"/>
      <w:basedOn w:val="Normal"/>
      <w:next w:val="Normal"/>
      <w:rPr>
        <w:b/>
        <w:sz w:val="32"/>
        <w:sz-cs w:val="32"/>
      </w:rPr>
    </w:style>
  </w:styles>
  
  <w:body>
    <wx:sect>
      <w:p>
        <w:pPr>
          <w:pStyle w:val="Heading1"/>
          <w:jc w:val="center"/>
        </w:pPr>
        <w:r>
          <w:t>${title}</w:t>
        </w:r>
      </w:p>
      
      <w:p>
        <w:pPr>
          <w:pStyle w:val="Normal"/>
        </w:pPr>
        <w:r>
          <w:t>Generated by ${author} - ${company}</w:t>
        </w:r>
      </w:p>
      
      <w:p>
        <w:pPr>
          <w:pStyle w:val="Normal"/>
        </w:pPr>
        <w:r>
          <w:t>Date: ${new Date().toLocaleDateString()}</w:t>
        </w:r>
      </w:p>
      
      <w:p>
        <w:pPr>
          <w:pStyle w:val="Normal"/>
        </w:pPr>
        <w:r>
          <w:t> </w:t>
        </w:r>
      </w:p>
      
      <w:p>
        <w:pPr>
          <w:pStyle w:val="Normal"/>
        </w:pPr>
        <w:r>
          <w:t>${plainText.substring(0, 10000)}</w:t>
        </w:r>
      </w:p>
      
      ${plainText.length > 10000 ? `
      <w:p>
        <w:pPr>
          <w:pStyle w:val="Normal"/>
        </w:pPr>
        <w:r>
          <w:t>[Content truncated for demonstration. Full content available in HTML/PDF export.]</w:t>
        </w:r>
      </w:p>
      ` : ''}
      
      <w:p>
        <w:pPr>
          <w:pStyle w:val="Normal"/>
        </w:pPr>
        <w:r>
          <w:t> </w:t>
        </w:r>
      </w:p>
      
      <w:p>
        <w:pPr>
          <w:pStyle w:val="Normal"/>
          <w:jc w:val="center"/>
        </w:pPr>
        <w:r>
          <w:t>--- End of Report ---</w:t>
        </w:r>
      </w:p>
    </wx:sect>
  </w:body>
</w:wordDocument>`
  
  // Convert to Blob and trigger download
  const blob = new Blob([docxContent], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' })
  const url = URL.createObjectURL(blob)
  
  const a = document.createElement('a')
  a.href = url
  a.download = fileName
  document.body.appendChild(a)
  a.click()
  
  // Cleanup
  setTimeout(() => {
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }, 100)
}

/**
 * Alternative: Create a more complete DOCX using JSZip for proper Office Open XML structure
 * This creates a .docx file (which is a ZIP archive containing XML files)
 */
export async function exportDocxAdvanced(html: string, options: ExportOptions = {}): Promise<void> {
  try {
    // Try to use JSZip if available
    // @ts-ignore - JSZip import might vary by version
    const JSZipModule = await import('jszip')
    // In some versions JSZip is the default export, in others it's not
    // @ts-ignore - TypeScript doesn't know the exact structure
    const JSZip = JSZipModule.default ? JSZipModule.default : JSZipModule
    
    const fileName = options.fileName || `report-${Date.now()}.docx`
    const plainText = htmlToPlainText(html)
    
    // Create a new ZIP archive
    // @ts-ignore - TypeScript doesn't know the exact constructor
    const zip = new JSZip()
    
    // Add minimal required files for a DOCX
    zip.file('[Content_Types].xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>`)
    
    // Add relationships
    zip.folder('_rels')?.file('.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>`)
    
    // Add word document
    zip.folder('word')?.file('document.xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    <w:p>
      <w:r>
        <w:t>${plainText.substring(0, 5000)}</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:r>
        <w:t>Generated by Oscar AI - Arboricultural Report System</w:t>
      </w:r>
    </w:p>
  </w:body>
</w:document>`)
    
    // Add word relationships
    zip.folder('word/_rels')?.file('document.xml.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
</Relationships>`)
    
    // Generate the ZIP file
    const blob = await zip.generateAsync({ type: 'blob' })
    const url = URL.createObjectURL(blob)
    
    const a = document.createElement('a')
    a.href = url
    a.download = fileName
    document.body.appendChild(a)
    a.click()
    
    // Cleanup
    setTimeout(() => {
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    }, 100)
    
  } catch (error) {
    console.error('Failed to create advanced DOCX:', error)
    // Fall back to simple DOCX
    await exportDocx(html, options)
  }
}

/**
 * Main export function - tries advanced method first, falls back to simple
 */
export async function exportToDocx(html: string, fileName?: string): Promise<void> {
  const options: ExportOptions = {
    fileName: fileName || `report-${new Date().toISOString().split('T')[0]}.docx`,
    title: 'Arboricultural Report',
    author: 'Oscar AI',
    company: 'Arboricultural Services Ltd'
  }
  
  try {
    await exportDocxAdvanced(html, options)
  } catch (error) {
    console.warn('Advanced DOCX export failed, using simple method:', error)
    await exportDocx(html, options)
  }
}