// Auto-generated version information
// This file is generated at build time by generate-version.cjs script
// DO NOT EDIT THIS FILE MANUALLY

export const APP_VERSION = '1.0.0';
export const COMMIT_HASH = '2e9e7ff';
export const BUILD_TIMESTAMP = '2026-02-16T22:35:37.675Z';
export const BUILD_VERSION = `v${APP_VERSION} (${COMMIT_HASH})`;

// For display in UI
export function getVersionInfo() {
	return {
		version: APP_VERSION,
		commit: COMMIT_HASH,
		timestamp: BUILD_TIMESTAMP,
		full: BUILD_VERSION
	};
}
