// Auto-generated version information
// This file is generated at build time by generate-version.cjs script
// DO NOT EDIT THIS FILE MANUALLY

export const APP_VERSION = '2.0.0';
export const COMMIT_HASH = 'f1f404c';
export const BUILD_TIMESTAMP = '2026-02-23T19:11:17.180Z';
export const BUILD_VERSION = `v${APP_VERSION} (${COMMIT_HASH})`;

// For display in UI
export function getVersionInfo() {
	return {
		version: APP_VERSION,
		commit: COMMIT_HASH,
		timestamp: BUILD_TIMESTAMP,
		full: BUILD_VERSION
	};
}
